"""add document summary

Revision ID: 2e5d03a0827d
Revises: 5c0278fbda54
Create Date: 2026-08-30 13:51:35.372880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e5d03a0827d'
down_revision: Union[str, Sequence[str], None] = '5c0278fbda54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('character_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'character_count')
    op.drop_column('documents', 'word_count')
    op.drop_column('documents', 'summary')
    # ### end Alembic commands ###
